name: covision
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - jupyter
  - matplotlib
  - opencv
  - pandas
  - pytorch::pytorch
  - pytorch::torchvision
  - mlflow
  - tqdm
