data_dir: data_cla/
save_path: models_cla/
train_test_split: 0.8
train_val_split: 0.8
sequences: ['11', '10', '01', '00']
diagnosis_map: {'11': 1, '10': 0, '01': 99, '00': 99}
crop_locs: [0.1, 0.5, 0.9]
membrane_shape: [160, 480]
zone_shape: [160, 160]
