data_args:
    data_dir: 'data_seg/'
    save_path: 'models_seg/'
    train_test_split: 0.8
    train_val_split: 0.8
    classes: ['background', 'kit', 'membrane']
    class_ids: [0, 1, 2]
    class_colors: [[255, 0, 0], [0, 0, 255], [0, 255, 0]]
    resize_height: 800
transformation_args:
    rotate_limit: 80
    rotate_p: 0.8
    horizontal_flip_p: 0.5
    blur_limit: 5
    blur_p: 0.8
    color_jitter_brightness: 0.1
    color_jitter_contrast: 0.1
    color_jitter_saturation: 0.1
    color_jitter_p: 0.5
    affine_scale: [1, 1.5]
    affine_translate_percent: [-0.1, 0.1]
    affine_p: 0.5
    downscale_min: 0.20
    downscale_max: 0.35
    downscale_p: 0.5
    gauss_noise_var_limit: [50, 100]
    gauss_noise_p: 0.5
    perspective_scale: [0.05, 0.1]
    perspective_p: 0.5
evaluation_args:
    score_thresholds: [0.85, 0.85]
    mask_thresholds: [0.7, 0.7]
